name: 'Recovery Compiler For Github Actions' 
author: 'ElytrA8' 
description: 'Universal Recovery Compiler' 
runs:
  using: "composite"
  steps:
    - run: curl -sL https://github.com/rokibhasansagar/slimhub_actions/raw/main/cleanup.sh | bash
      shell: bash
    - run: $GITHUB_ACTION_PATH/prepare.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/builder.sh
      shell: bash
branding:
  icon: 'box'
  color: 'black'
