name: 'Recovery Compiler For Github Actions' 
author: 'ElytrA8' 
description: 'Universal Recovery Compiler'

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/cleanup.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/prepare.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/builder.sh
      shell: bash
branding:
  icon: 'box'
  color: 'black'
